# Generated by Django 2.0 on 2018-01-11 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djinn_contenttypes.models.relatable
import djinn_contenttypes.models.sharing
import pgauth.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pgauth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('changed', models.DateTimeField(auto_now=True, verbose_name='Changed')),
                ('removed_creator_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Creator naam')),
                ('userkeywords', models.CharField(blank=True, max_length=500, null=True, verbose_name='Keywords')),
                ('is_tmp', models.BooleanField(default=False, verbose_name='Temporary')),
                ('text', models.TextField(verbose_name='Text')),
                ('start_date', models.DateField(verbose_name='Start date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Start time')),
                ('end_date', models.DateField(blank=True, default=None, null=True, verbose_name='End date')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='End time')),
                ('location', models.CharField(max_length=200, verbose_name='Location')),
                ('link', models.CharField(max_length=200, verbose_name='Link')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_changed_by', to=settings.AUTH_USER_MODEL)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_creator', to=settings.AUTH_USER_MODEL)),
                ('parentusergroup', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_parentusergroup', to='pgauth.UserGroup')),
            ],
            options={
                'ordering': ('-start_date',),
            },
            bases=(models.Model, pgauth.base.LocalRoleMixin, djinn_contenttypes.models.sharing.SharingMixin, djinn_contenttypes.models.relatable.RelatableMixin),
        ),
    ]
