# Generated by Django 2.0.13 on 2019-05-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description_feed',
            field=models.TextField(blank=True, help_text='Samenvatting specifiek voor tonen op infoscherm(en)', null=True, verbose_name='Infoscherm samenvatting'),
        ),
        migrations.AddField(
            model_name='event',
            name='publish_for_feed',
            field=models.BooleanField(default=False, help_text='Item tonen op infoscherm(en)', verbose_name='Toon op infoschermen'),
        ),
    ]
