# Generated by Django 2.0.13 on 2019-10-03 10:41

from django.db import migrations, models
import django.db.models.deletion
import image_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_events', '0003_auto_20190919_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_feed',
            field=models.ForeignKey(blank=True, help_text='Image for the rss-feed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image', to='djinn_contenttypes.ImgAttachment'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_feed_crop',
            field=image_cropping.fields.ImageRatioField('image_feed__image', '1000x500', adapt_rotation=False, allow_fullsize=False, free_crop=False, help_text='Part of the image to use in the rss-feed', hide_image_field=False, size_warning=True, verbose_name='Foto uitsnede'),
        ),
    ]
