# Generated by Django 2.0.13 on 2019-10-22 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djinn_events', '0005_auto_20191015_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_feed',
            field=models.ForeignKey(blank=True, help_text='Image for the rss-feed. Minimal width is 1920px, minimal heigt 500px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='event_image', to='djinn_contenttypes.ImgAttachment'),
        ),
    ]
